name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install XcodeGen
      run: brew install xcodegen

    - name: Generate Xcode Project
      run: xcodegen generate

    - name: Build
      run: |
        xcodebuild build \
          -project xNotes.xcodeproj \
          -scheme xNotes \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          CODE_SIGNING_ALLOWED=NO
